package fr.tfl.store.bean;

// Generated 2 mars 2015 10:44:38 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonFilter;

/**
 * AclStore generated by hbm2java
 */
@JsonFilter("AclStoreFilter")
@Entity
@Table(name = "acl_store", catalog = "store")
public class AclStore implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private int version;
	private Droit droit;
	private Profil profil;
	private Ressource ressource;
	private String label;

	public AclStore() {
	}

	public AclStore(Droit droit, Profil profil, Ressource ressource,
			String label) {
		this.droit = droit;
		this.profil = profil;
		this.ressource = ressource;
		this.label = label;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "right_1", nullable = false)
	public Droit getDroit() {
		return this.droit;
	}

	public void setDroit(Droit droit) {
		this.droit = droit;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "profil", nullable = false)
	public Profil getProfil() {
		return this.profil;
	}

	public void setProfil(Profil profil) {
		this.profil = profil;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ressource", nullable = false)
	public Ressource getRessource() {
		return this.ressource;
	}

	public void setRessource(Ressource ressource) {
		this.ressource = ressource;
	}

	@Column(name = "label", nullable = false, length = 100)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

}
