package fr.tfl.store.bean;
// Generated 22 ao�t 2016 09:44:22 by Hibernate Tools 5.1.0.Beta1

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

import fr.tfl.store.persistance.IDomainEntity;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", schema = "public")
public class Commande implements IDomainEntity<UUID> {

	@Type(type="pg-uuid")
	private UUID id;
	private Product product;
	private String reference;

	public Commande() {
	}

	public Commande(Product product, String reference) {
		this.product = product;
		this.reference = reference;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "product"))
	@Id
	@GeneratedValue(generator = "generator")
	@Type(type="pg-uuid")
	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "reference", nullable = false)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

}
