package fr.tfl.store.bean;

// Generated 2 mars 2015 10:44:38 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Droit generated by hbm2java
 */
@Entity
@Table(name = "droit", catalog = "store")
public class Droit implements java.io.Serializable {

	private Integer id;
	private int version;
	private String lable;
	private String code;
	private Set<AclStore> aclStores = new HashSet<AclStore>(0);

	public Droit() {
	}

	public Droit(String lable, String code) {
		this.lable = lable;
		this.code = code;
	}

	public Droit(String lable, String code, Set<AclStore> aclStores) {
		this.lable = lable;
		this.code = code;
		this.aclStores = aclStores;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "lable", nullable = false, length = 20)
	public String getLable() {
		return this.lable;
	}

	public void setLable(String lable) {
		this.lable = lable;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "droit")
	public Set<AclStore> getAclStores() {
		return this.aclStores;
	}

	public void setAclStores(Set<AclStore> aclStores) {
		this.aclStores = aclStores;
	}

}
