package fr.tfl.store.bean;
// Generated 22 ao�t 2016 09:44:22 by Hibernate Tools 5.1.0.Beta1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

import fr.tfl.store.persistance.IDomainEntity;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", schema = "public")
public class Product implements IDomainEntity<UUID> {

	@Type(type="pg-uuid")
	private UUID id;
	private String label;
	private String reference;
	private Integer status;
	private Integer quantity;
	private Commande commande;
	private double price;
	private String idpicture;

	@Column(name = "price")
	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Product() {
	}

	public Product(UUID id) {
		this.id = id;
	}

	public Product(UUID id, String label, String reference, Integer status, Integer quantity,
			Commande commande) {
		this.id = id;
		this.label = label;
		this.reference = reference;
		this.status = status;
		this.quantity = quantity;
		this.commande = commande;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@Type(type="pg-uuid")
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "label", length = 40)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "reference")
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "product")
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}
	
	@Column(name = "idpicture")
	public String getIdpicture() {
		return this.idpicture;
	}

	public void setIdpicture(String idpicture) {
		this.idpicture = idpicture;
	}


}
