package fr.tfl.store.bean;

// Generated 2 mars 2015 10:44:38 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

import com.fasterxml.jackson.annotation.JsonFilter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Profil generated by hbm2java
 */
@JsonFilter("ProfilFilter")  
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
@Entity
@Table(name = "profil", catalog = "store")
public class Profil implements java.io.Serializable {

	private Integer id;
	private int version;
	private String profil;
	private String label;
	private Set<AclStore> aclStores = new HashSet<AclStore>(0);

	public Profil() {
	}

	public Profil(String profil) {
		this.profil = profil;
	}

	public Profil(String profil, String label, Set<AclStore> aclStores,
			Set<User> users) {
		this.profil = profil;
		this.label = label;
		this.aclStores = aclStores;		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "profil", nullable = false, length = 10)
	public String getProfil() {
		return this.profil;
	}

	public void setProfil(String profil) {
		this.profil = profil;
	}

	@Column(name = "label", length = 20)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<AclStore> getAclStores() {
		return this.aclStores;
	}

	public void setAclStores(Set<AclStore> aclStores) {
		this.aclStores = aclStores;
	}
	
}
