package demo;
// Generated 30 ao�t 2016 23:51:02 by Hibernate Tools 5.1.0.Beta1

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", schema = "public")
public class Produit implements java.io.Serializable {

	private Serializable id;
	private String label;
	private String reference;
	private Integer status;
	private Integer quantity;
	private Commande commande;

	public Produit() {
	}

	public Produit(Serializable id) {
		this.id = id;
	}

	public Produit(Serializable id, String label, String reference, Integer status, Integer quantity,
			Commande commande) {
		this.id = id;
		this.label = label;
		this.reference = reference;
		this.status = status;
		this.quantity = quantity;
		this.commande = commande;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	@Column(name = "label", length = 40)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "reference")
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "produit")
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

}
