package demo;
// Generated 30 ao�t 2016 23:51:02 by Hibernate Tools 5.1.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur", schema = "public")
public class Utilisateur implements java.io.Serializable {

	private long id;
	private int version;
	private String name;
	private String password;
	private String mail;
	private int pid;
	private String firstname;
	private Integer age;
	private Date lastupdate;
	private Date birthdate;
	private Long idpicture;

	public Utilisateur() {
	}

	public Utilisateur(long id, String name, String password, String mail, int pid, String firstname) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.mail = mail;
		this.pid = pid;
		this.firstname = firstname;
	}

	public Utilisateur(long id, String name, String password, String mail, int pid, String firstname, Integer age,
			Date lastupdate, Date birthdate, Long idpicture) {
		this.id = id;
		this.name = name;
		this.password = password;
		this.mail = mail;
		this.pid = pid;
		this.firstname = firstname;
		this.age = age;
		this.lastupdate = lastupdate;
		this.birthdate = birthdate;
		this.idpicture = idpicture;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "mail", nullable = false, length = 20)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "pid", nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdate", length = 29)
	public Date getLastupdate() {
		return this.lastupdate;
	}

	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthdate", length = 13)
	public Date getBirthdate() {
		return this.birthdate;
	}

	public void setBirthdate(Date birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "idpicture")
	public Long getIdpicture() {
		return this.idpicture;
	}

	public void setIdpicture(Long idpicture) {
		this.idpicture = idpicture;
	}

}
